#!/bin/bash

source /etc/sqlfire-server.conf

# basics
SQLF_ARGS="-initial-heap=${SQLF_INITIAL_HEAP} -max-heap=${SQLF_MAX_HEAP}"
SQLF_ARGS="$SQLF_ARGS -user=${SQLF_DB_USERNAME} -password=${SQLF_DB_PASSWORD}"
SQLF_ARGS="$SQLF_ARGS -server-groups=${SQLF_SERVER_GROUPS}"
SQLF_ARGS="$SQLF_ARGS -dir=${SQLF_SERVER_DATA_DIR}"
SQLF_ARGS="$SQLF_ARGS -classpath=${APP_LIB_DIR}:${APP_LIB_DIR}/*"
SQLF_ARGS="$SQLF_ARGS -locators=${LOCATOR_IP_STRING}"
SQLF_ARGS="$SQLF_ARGS -client-bind-address=${BIND_ADDRESS} -client-port=${CLIENT_PORT}"
SQLF_ARGS="$SQLF_ARGS -log-file=${SQLF_SERVER_LOG_FILE}"
SQLF_ARGS="$SQLF_ARGS -J-Xss384k"
SQLF_ARGS="$SQLF_ARGS -J-XX:PermSize=256m -J-XX:MaxPermSize=256m"
SQLF_ARGS="$SQLF_ARGS -J-XX:NewRatio=4 -J-XX:SurvivorRatio=8"
SQLF_ARGS="$SQLF_ARGS -J-XX:+UseParNewGC -J-XX:+UseConcMarkSweepGC"
SQLF_ARGS="$SQLF_ARGS -J-XX:+DisableExplicitGC"
SQLF_ARGS="$SQLF_ARGS -J-XX:CMSInitiatingOccupancyFraction=60"
SQLF_ARGS="$SQLF_ARGS -J-javaagent:${SQLF_HOME}/lib/sqlfire.jar"
# socket tuning
SQLF_ARGS="$SQLF_ARGS -socket-buffer-size=262144"
# 512k SQLF_ARGS="$SQLF_ARGS -socket-buffer-size=524288"
# stats (turn off in prod)
SQLF_ARGS="$SQLF_ARGS -enable-time-statistics=true"
SQLF_ARGS="$SQLF_ARGS -statistic-archive-file=${APP_STATISTIC_ARCHIVE_FILE}"
SQLF_ARGS="$SQLF_ARGS -statistic-sampling-enabled=true"
SQLF_ARGS="$SQLF_ARGS -archive-disk-space-limit=1000"
SQLF_ARGS="$SQLF_ARGS -archive-file-size-limit=100"
# log file and dir limits
SQLF_ARGS="$SQLF_ARGS -log-disk-space-limit=1000"
SQLF_ARGS="$SQLF_ARGS -log-file-size-limit=100"
# remote jmx
SQLF_ARGS="$SQLF_ARGS -J-Dcom.sun.management.jmxremote"
SQLF_ARGS="$SQLF_ARGS -J-Dcom.sun.management.jmxremote.port=${JMX_PORT}"
SQLF_ARGS="$SQLF_ARGS -J-Dcom.sun.management.jmxremote.authenticate=false"
SQLF_ARGS="$SQLF_ARGS -J-Dcom.sun.management.jmxremote.ssl=false"
# logs
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.log-file=${APP_LOG_FILE}"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.error-log-file=${APP_ERROR_LOG_FILE}"
# sqlserver db
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.mdo.case-sensitivity=upper"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.mdo.catalog-name=???"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.mdo.schema-name=???"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.mdo.username=${APP_DB_MDO_USERNAME}"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.mdo.password=${APP_DB_MDO_PASSWORD}"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.mdo.driverClassName=${APP_DB_MDO_DRIVER_CLASS_NAME}"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.mdo.url='${APP_DB_MDO_URL}'"
# db/2 db
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.db2.case-sensitivity=upper"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.db2.catalog-name=???"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.db2.schema-name=???"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.db2.username=${APP_DB_DB2_USERNAME}"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.db2.password=${APP_DB_DB2_PASSWORD}"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.db2.driverClassName=${APP_DB_DB2_DRIVER_CLASS_NAME}"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.db2.url='${APP_DB_DB2_URL}'"
# sqlf embedded db
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.embedded.driverClassName=com.vmware.sqlfire.jdbc.EmbeddedDriver"
SQLF_ARGS="$SQLF_ARGS -J-Dorg.kp.data-source.embedded.url='jdbc:sqlfire:'"

SQLF=${SQLF_HOME}/bin/sqlf
SU="/bin/su -s /bin/sh"

start() {
    echo -n "Starting Pivotal SQLFire Server: "
    ${SU} ${SQLF_USER} -c "$SQLF server start ${SQLF_ARGS}"

    if [ $? = 0 ];then
        echo "SUCCESS"
        echo
    else
        echo "FAILURE"
        echo
    fi
}

stop() {
    echo -n "Shutting down Pivotal SQLFire Server: "
    ${SU} ${SQLF_USER} -c "$SQLF server stop -dir=${SQLF_SERVER_DATA_DIR}"

    if [ $? = 0 ];then
        echo "SUCCESS"
        echo
    else
        echo "FAILURE"
        echo
    fi
}

status() {
    ${SU} ${SQLF_USER} -c "$SQLF server status -dir=${SQLF_SERVER_DATA_DIR}"
}



case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: Pivotal SQLFire Server {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
